# Generated by Django 2.1.7 on 2019-04-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('create_time', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('modify_time', models.CharField(max_length=100)),
            ],
        ),
    ]
