# Generated by Django 2.1.7 on 2019-04-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mistake',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_id', models.IntegerField()),
                ('mistake_type', models.CharField(max_length=100)),
                ('mistake_grade', models.CharField(max_length=100)),
                ('mistake_detail', models.CharField(max_length=255)),
                ('find_time', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=255)),
                ('extends', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('create_time', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('create_time', models.CharField(max_length=100)),
                ('modify_time', models.CharField(max_length=100)),
                ('user_state', models.IntegerField()),
                ('user_role', models.IntegerField()),
            ],
        ),
    ]
