# Generated by Django 2.1.7 on 2019-04-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20190415_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='extends',
            field=models.CharField(max_length=2048),
        ),
    ]
